### ISSUE TITLE
Code review feedback

### ISSUE THREAD

**Issue by Bornittah** [brainconnect93/Bootstrap-portfolio#2]
You did well @brainconnect93
Please find the feedback from the reviewers

**Highlights**

- Meaningful commit messages
- Descriptive PR

**Requested changes**

- Please, Write a meaningful title for your pull request
- Use imperative verbs in commit messages.
- Kindly add linters to your project. Please refer to [this](https://github.com/microverseinc/linters-config) document
- Please add a professional README.md file to your repository. kindly refer to the sample provided [here](https://github.com/microverseinc/readme-template).

**Comment by brainconnect93** [comment]
done
