### ISSUE TITLE
Add linters

### ISSUE THREAD

**Issue by mirelapitt** [brainconnect93/Bootstrap-portfolio#3]
Hi,
Good job so far!
Kindly add the linters as the first commit of your project should be to add the linters.

**Comment by lazyCode-404** [comment]
Hello, 
You did a great job on the interface layout of your project.
Kindly work on your README file and update it with content about the project.
Please get rid of the unnecessary spaces in line 43 and 44 and line 179 and 180 in the index.html file for best coding practices.

**Comment by kelomo2502** [comment]
Good job guy,
I would only suggest you kindly look into the recommendations of other team members and see how you can implement some of them.
happy Coding!
